routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin'], function () {
    Route::get('/', 'AdminController@Home')->name('admin.home');
    Route::group(['middleware' => 'auth'], function () {
        Route::group(['middleware' => ['role:admin']], function () {
            Route::resource('page', 'PageController');
            Route::resource('product', 'ProductController');
            Route::post('product/reorder', 'ProductController@reorder')->name('product.reorder');
            Route::get('product/type/{type}', 'ProductController@index');
            Route::resource('order', 'OrderController');
            Route::resource('shipping', 'ShippingController');
            Route::resource('social', 'SocialMediaController');
            Route::resource('enquiry', 'EnquiryController');
            Route::resource('lead-conversion-types', 'LeadConversionTypeController');
            Route::resource('user', 'UserController');
            Route::resource('post', 'PostController');
            Route::resource('mainpage', 'MainPageController');
            Route::resource('voucher', 'VoucherController');
            Route::resource('inspireme', 'InspireMeController');
            Route::resource('settings', 'SettingsController');
            
            Route::get('/invoice/{order}', 'OrderController@invoice');

            # Slide controlls:
            Route::get('slider/slide/{slide}/remove-slide/', 'SliderController@removeSlide')->name('slider.remove-slide');
            Route::get('slider/slide/{slide}/remove-background/', 'SliderController@removeBackground')->name('slider.remove-slide-background');
            Route::get('slider/slide/{slide}/remove-item/', 'SliderController@removeItem')->name('slider.remove-slide-item');

            Route::get('email-templates', 'EmailTemplateController@index')->name('emailTemplates.index');
            Route::resource('email-template', 'EmailTemplateController');

            Route::get('video-post', 'PostController@vlogIndex'); 
            Route::post('video-post', 'PostController@storeVlog'); 
            Route::post('video-post/{postId}/delete', 'PostController@destroyVlog');
            Route::post('video-post/edit/{postId}', 'PostController@updateVlog');




            Route::get('video-post/{postId}/edit', 'PostController@editVlog');
            Route::get('video-post/create', 'PostController@createVlog');
            Route::get('mailing-list', 'EnquiryController@mailingListIndex')->name('mailinglist');


            Route::get('statistics', 'StatisticsController@getStatistics')->name('statistics');

            Route::get('profile', 'UserController@adminProfileIndex')->name('admin.profile');
            Route::post('update-profile/{user}', 'UserController@adminProfileUpdate');
            Route::get('logout', 'Auth\LoginController@logOut')->name('login.logout');

            Route::get('/module-sheet', 'AdminController@moduleSheet')->name('admin.module-sheet');
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*
*
*/

Route::post('/email-share', 'SocialMediaController@emailShare')->name('email.share');
Route::get('products/json','ProductsContoller@getProductsJson')->name('products.getJson');
Route::get('/shipping-json', 'ShippingController@getCountryJson')->name('shipping.getCountryJson');
Route::get('/share/{id}', 'MainPageController@share')->name('mainpage.share');
Route::get('/', 'MainPageController@home')->middleware('set.ip.currency')->name('home');
Route::get('home/', 'MainPageController@homeRedirect')->middleware('set.ip.currency')->name('homeRedirect');

Auth::routes();

Route::any('image-generate', 'ImageController@imageGenerate')->name('image.generate');

route::post('share-count', 'SocialMediaController@incrementShareCount')->name('socialmedia.incrementShare');
Route::get('join', 'Auth\LoginController@join')->name('login.join');
Route::get('signed-in/', 'Auth\LoginController@signedIn')->name('login.signedIn');
Route::get('accessories', 'ProductController@indexAccessories')->name('accessories');
Route::get('aboutus', 'MainPageController@aboutUs')->name('aboutus');
Route::get('differences', 'MainPageController@differences' )->name('differences');
Route::get('contact', 'MainPageController@contact')->name('contact');
Route::get('contact-success', 'MainPageController@contactSuccess')->name('contact-success');
// Route::get('customise', 'CustomiserController@index')->name('customise');
Route::get('our-straps', 'CustomiserController@index')->name('customise');

//TODO: CART DISABLED FOR NOW
Route::get('cart', 'CartController@cart')->name('cart');

Route::post('apply-voucher', 'VoucherController@apply')->name('voucher.apply');
Route::get('remove-voucher', 'VoucherController@remove')->name('voucher.remove');
// Route::get('cart', function () {
//     return redirect()->back();
// })->name('cart');

Route::post('checkout', 'CheckoutController@post')->name('checkout');
Route::get('checkout-login', 'CheckoutController@checkoutLogin')->name('checkout-login');
Route::post('checkout/guest', 'CheckoutController@guest')->name('checkout.guest');

Route::post('checkout/complete', 'CheckoutController@checkout')->name('checkout.complete');
Route::get('completed/', 'CheckoutController@completed')->name('checkout.completed');

Route::get('checkout/failed', 'CheckoutController@checkoutFailed')->name('checkout.failed');

Route::get('order-success', 'OrderController@orderSuccess')->name('order-success');

Route::post('enquiry/send', 'EnquiryController@send')->name('enquiry.send');
Route::post('newsletter/subscribe', 'EnquiryController@signupForNewsletter')->name('newsletter.subscribe');

Route::get('unsubscribe/{email}', 'EnquiryController@unsubscribeFromNewsletter');


Route::post('cart/remove', 'CartController@remove')->name('cart.remove');
Route::post('cart/qty', 'CartController@qty')->name('cart.qty');
Route::post('cart/{product}', 'CartController@add')->name('cart.add');
Route::get('cart/destroy', 'CartController@destroy')->name('cart.destroy');
Route::get('cart/set/currency/{currency}', 'CartController@setCurrency')->name('cart.setCurrency');

Route::post('customiser/assemble', 'CustomiserController@assemble')->name('customiser.assemble');

Route::resource('customiser', 'CustomiserController');


Route::get('blog', 'PostController@allPosts')->name('blog');
Route::get('blog/{post}', 'PostController@show')->name('blog.show');
Route::get('blog/{post}/share/{socialMedia}', 'PostController@share')->name('blog.share');

Route::get('mail-test/order/{order}/','CheckoutController@mailTest')->name('checkout.mailTest');
Route::get('mail-test/order-admin/{order}/', 'CheckoutController@adminMailTest')->name('checkout.adminMailTest');
// Pages Controller to control user defined pages:
Route::get('{slug}', 'PageController@show');

resources/views/atrium/pages/email-template-edit.blade.php
@extends('atrium.layouts.app')

@section('view-header__content')
  <h1 class="view-title">Edit Email template: {{ $emailTemplate->name }}</h1>
@endsection

@section('view-main__body')

<form class="view-main__content__editor-form form--standard is-flex-grid" action="{{ route('email-template.update', $emailTemplate) }}" method="POST">
  <input type="hidden" name="_method" value="PUT">
  {{ csrf_field() }}
<section class="view-main__section">
  <header class="view-main__section__header">
    <h3 class="view-main__section__title">Email template</h3>
    <p>Available variables to use:</p>
    <table class="view-main__section__content variables__list">
      <tbody>
        <tr class="variables__list-header">
          <th>Variable Name</th>
          <th>Variable Description</th>
        </tr>
        <tr>
          <td><strong>{customer.name}</strong></td>
          <td>- Prints customer's name in template.</td>
        </tr>
        <tr>
          <td><strong>{customer.email}</strong></td>
          <td>- Prints customer's email in template.</td>
        </tr>
        <tr>
          <td><strong>{order.number}</strong></td>
          <td>- Prints order number.</td>
        </tr>
          @if($emailTemplate->id == 1)
            <tr>
              <td><strong>{order.tracking_number}</strong></td>
              <td>- Prints tracking number in template.</td>
            </tr>
            <tr>
              <td><strong>{order.vouchers}</strong></td>
              <td>- Includes list of voucher codes (if purchased by user).</td>
            </tr>
          @elseif ($emailTemplate->id == 2 || $emailTemplate->id == 3)
            <tr>
              <td><strong>{order.products}</strong></td>
              <td>- Prints a simple list with products.</td>
            </tr>
            <tr>
              <td><strong>{order.products.withImages}</strong></td>
              <td>- Prints simple list with products and images.</td>
            </tr>
            <tr>
              <td><strong>{order.products.details}</strong></td>
              <td>- Prints detailed list of products for admin use.</td>
            </tr>
            <tr>
              <td><strong>{order.products.details.withImages}</strong></td>
              <td>- Prints Simple list with products and images.</td>
            </tr>
            <tr>
              <td><strong>{order.addresses}</strong></td>
              <td>- Prints shipping and billing addresses.</td>
            </tr>
          @endif
      </tbody>
    </table>
  </header>


  <div class="flex-row">
    <div class="flex-row">
      <div class="input--textarea flex-6-fr {{ $errors->has('content') ? ' has-error' : ''}}">
        <label for="ckeditor">Content</label>
        <textarea name="body" id="ckeditor" rows="15">{!! old('body') ? old('body') : $emailTemplate->body !!}</textarea>
      </div>
    </div>
  </div>

</section>

{{-- <section class="view-main__section">
  <header class="view-main__section__header">
    <h3 class="view-main__section__title">Email template options</h3>
  </header>

  <div class="flex-row">

    <div class="input--text flex-2-fr">
      <label for="ef-post-title">Send email copy to this email</label>
      <input name="ccTo" id="ef-post-titletag" type="text" placeholder="" value="{{ (old('ccTo')) ? old('ccTo') : $emailTemplate->ccTo }}"/>
    </div>

    <div class="input--toggle">
      <input name="ccCopy" type="checkbox" class="input--toggle__checkbox" id="toggle-second-toggle" @if($emailTemplate->ccCopy) checked @endif/>
      <label class="input--toggle__label" for="toggle-second-toggle">Get copy of this email</label>
    </div>

  </div>

</section> --}}

<div class="button-group">
  <button type="submit" class="btn--std--primary">
    <svg width="16" height="16" viewbox="0 0 16 16"><use xlink:href="#icon-check"></use></svg>
    <span class="button-label">Save</span>
  </button>
  <a href="{{ url('admin/email-templates') }}" class="btn--std">
    <svg width="16" height="16" viewbox="0 0 16 16"><use xlink:href="#icon-close"></use></svg>
    <span class="button-label">Cancel</span>
  </a>
</div>

</form>
@endsection

{{-- @section('widget-panel__content')

  <section class="widget-panel__section" data-section-name="actions">
    <h3 class="widget-panel__section__title">Actions</h3>
    <ul class="widget-panel__link-group">
      <form class="" action="{{ url('admin/page', $emailTemplate) }}" method="post" onsubmit="return confirm_delete();">
        <input type="hidden" name="_method" value="DELETE">
        {{ csrf_field() }}
        <li><button type="submit" class="widget-panel__link" href="">Delete this page</button></li>
      </form>
    </ul>
  </section>

@endsection --}}

resources/views/atrium/pages/enquiry-show.blade.php
@extends('atrium.layouts.app')

@section('view-header__content')
  <h1 class="view-title">Enquiry #{{ $enquiry->id }}</h1>
@endsection

@section('view-main__body')

<section class="view-main__section">
  <header class="view-main__section__header">
    <h3 class="view-main__section__title">Topic: {{ $enquiry->topic }}</h3>
  </header>

  <div class="flex-row">
    <div class="input--text flex-3-fr {{ $errors->has('name') ? ' has-error' : ''}}">
      <label for="ef-product-name">Name</label>
      <p>{{ $enquiry->firstName }} {{ $enquiry->lastName }}</p>
    </div>

    <div class="input--text flex-2-fr">
      <label for="ef-number">Email</label>
      <p>{{ $enquiry->email }}</p>
    </div>

    <div class="input--text flex-2-fr">
      <label for="ef-number">Order Number</label>
      <p>{{ $enquiry->orderNumber }}</p>
    </div>

  </div>

  <div class="flex-row">
    <div class="input--textarea flex-5-fr {{ $errors->has('description') ? ' has-error' : ''}}">
      <label for="ckeditor">User Message</label>
      <p>{{ $enquiry->message }}</p>
    </div>
  </div>

</section>

<div class="button-group">
  {{-- <button type="submit" class="btn--std--primary">
    <svg width="16" height="16" viewbox="0 0 16 16"><use xlink:href="#icon-check"></use></svg>
    <span class="button-label">Save</span>
  </button> --}}
  <a href="{{ url('admin/enquiry') }}" class="btn--std">
    <svg width="16" height="16" viewbox="0 0 16 16"><use xlink:href="#icon-close"></use></svg>
    <span class="button-label">Cancel</span>
  </a>
</div>
@endsection

@section('widget-panel__content')

  <section class="widget-panel__section" data-section-name="actions">
    <h3 class="widget-panel__section__title">Actions</h3>
    <ul class="widget-panel__link-group">
      <form class="" action="{{ url('admin/enquiry', $enquiry) }}" method="post" onsubmit="return confirm_delete();">
        <input type="hidden" name="_method" value="DELETE">
        {{ csrf_field() }}
        <li><button type="submit" class="widget-panel__link" href="">Delete this enquiry</button></li>
      </form>
    </ul>
  </section>

@endsection

resources/views/atrium/pages/inspireme-edit.blade.php
@extends('atrium.layouts.app')

@section('view-header__content')
  <h1 class="view-title">Edit Inspire-Me Preset</h1>
@endsection

@section('view-main__body')

<section class="view-main__section" id="app">

  <strap-customiser :source-data='{!! $data !!}' :preset='{!! $preset !!}' custom-text="" mode="admin"></strap-customiser>

</section>

<style>
    .details:not(.open) summary~* { display: none; }
</style>

@endsection

resources/views/atrium/pages/leadconvtypes-index.blade.php
@extends('atrium.layouts.app')

@section('view-header__content')
  <h1 class="view-title">Lead Conversion Types</h1>
@endsection

@section('view-main__body')

  <section class="view-main__content">
    <div class="table-container is-tr-clickable">
      {{-- <p><span class="u-big-inline-number">{{ $count }}</span> entries in total.</p> --}}
      <script type="text/x-template" id="grid-template">
        <table class="table--standard">
          <thead>
            <tr>
              <!-- <th class="th-permalink-arrow"></th> -->
              <th class="sortable-th" v-for="key in columns"
                @click="sortBy(key)"
                :class="sortOrders[key] > 0 ? 'is-asc' : 'is-dsc'"
                >
                <span class="sorter-toggle" :class="sortOrders[key] > 0 ? 'asc' : 'dsc'">
                </span>
                @{{ key | tableHeadPrepper }}
              </th>
              <th>
                Actions
              </th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="entry in filteredData" @click="goToPermalink(entry)">

              <template v-for="key in columns">
                <td v-if="key == 'link'" class="td-permalink-arrow">
                  <a :href='entry[key]'><svg width="12" height="12" viewbox="0 0 12 12">
                    <use xlink:href="#icon-arrow" /></svg>
                  </a>
                </td>
                <td v-else-if="key == 'last_logged_in' && key.last_logged_in != 'N/A'">
                  @{{ entry.last_logged_in.created_at }}
                </td>
                <td v-else>@{{ entry[key] }}</td>
              </template>

              <td>
                <span class="item-actions">
                  <a :href="'lead-conversion-types/' + entry.id + '/edit'" title="">Edit</a>
                  &nbsp;
                  <form class="" :action="'lead-conversion-types/' + entry.id" method="post" onsubmit="return confirm_delete();">
                    <input type="hidden" name="_method" value="DELETE">
                    {{ csrf_field() }}
                    <button type="submit" class="" href="">Delete</button>
                  </form>
                </span>
              </td>
            </tr>
          </tbody>
        </table>
      </script>

      <!-- table root element -->
      <div id="table" class="sortable-table">
        <form id="search" class="table-filter-form">
          <input class="table-filter-input" type="search" name="query" placeholder="Filter results..." v-model="searchQuery" id="table-filter-input">

        </form>
        <table-grid
          :data="gridData"
          :columns="gridColumns"
          :filter-key="searchQuery">
        </table-grid>
      </div>

      <script>
          // register the grid component
          Vue.component('table-grid', {
            template: '#grid-template',
            props: {
              data: Array,
              columns: Array,
              filterKey: String
            },
            data: function () {
              var sortOrders = {}
              this.columns.forEach(function (key) {
                sortOrders[key] = 1
              })
              return {
                sortKey: '',
                sortOrders: sortOrders
              }
            },
            computed: {
              filteredData: function () {
                var sortKey = this.sortKey
                var filterKey = this.filterKey && this.filterKey.toLowerCase()
                var order = this.sortOrders[sortKey] || 1
                var data = this.data
                if (filterKey) {
                  data = data.filter(function (row) {
                    return Object.keys(row).some(function (key) {
                      return String(row[key]).toLowerCase().indexOf(filterKey) > -1
                    })
                  })
                }
                if (sortKey) {
                  data = data.slice().sort(function (a, b) {
                    a = a[sortKey]
                    b = b[sortKey]
                    return (a === b ? 0 : a > b ? 1 : -1) * order
                  })
                }
                return data
              }
            },
            filters: {
              tableHeadPrepper: function (str) {
                return (str.charAt(0).toUpperCase() + str.slice(1)).replace(/_/g, ' ')
              }
            },
            methods: {
              sortBy: function (key) {
                this.sortKey = key
                this.sortOrders[key] = this.sortOrders[key] * -1
              },
              goToPermalink: function(entry) {
                if (entry.link !== undefined) {
                  window.location.href = entry.link;
                }
              }
            },
            created: function() {
            }
          })

          // bootstrap the table
          var table = new Vue({
            el: '#table',
            data: {
              searchQuery: '',
              gridColumns: {!! json_encode( $keys ) !!},
              gridData: {!! json_encode( $data ) !!}
            }
          })

        </script>
    </div>
  </section>

@endsection

@section('widget-panel__content')

  <section class="widget-panel__section" data-section-name="actions">
    <h3 class="widget-panel__section__title">Actions</h3>
    <ul class="widget-panel__link-group">
      <li><a class="widget-panel__link" href="{{ route('lead-conversion-types.create') }}">Create a new type</a></li>
    </ul>
  </section>

@endsection

resources/views/atrium/pages/mainpages-index.blade.php
@extends('atrium.layouts.app')

@section('view-header__content')
  <h1 class="view-title">Main Pages</h1>
@endsection

@section('view-main__body')

  <section class="view-main__content">
    <div class="table-container is-tr-clickable">
      {{-- <p><span class="u-big-inline-number">{{ $count }}</span> entries in total.</p> --}}
      <script type="text/x-template" id="grid-template">
        <table class="table--standard">
          <thead>
            <tr>
              <!-- <th class="th-permalink-arrow"></th> -->
              <th class="sortable-th" v-for="key in columns"
                @click="sortBy(key)"
                :class="sortOrders[key] > 0 ? 'is-asc' : 'is-dsc'"
                >
                <span class="sorter-toggle" :class="sortOrders[key] > 0 ? 'asc' : 'dsc'">
                </span>
                @{{ key | tableHeadPrepper }}
              </th>
              <th>
                Actions
              </th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="entry in filteredData" @click="goToPermalink(entry)">

              <template v-for="key in columns">
                <td v-if="key == 'link'" class="td-permalink-arrow">
                  <a :href='entry[key]'><svg width="12" height="12" viewbox="0 0 12 12">
                    <use xlink:href="#icon-arrow" /></svg>
                  </a>
                </td>
                <td v-else-if="key == 'last_logged_in' && key.last_logged_in != 'N/A'">
                  @{{ entry.last_logged_in.created_at }}
                </td>
                <td v-else>@{{ entry[key] }}</td>
              </template>

              <td>
                <span class="item-actions">
                  <a :href="'/admin/mainpage/' + entry.id + '/edit'" title="">Edit</a>
                </span>
              </td>
            </tr>
          </tbody>
        </table>
      </script>

      <!-- table root element -->
      <div id="table" class="sortable-table">
        <form id="search" class="table-filter-form">
          <input class="table-filter-input" type="search" name="query" placeholder="Filter results..." v-model="searchQuery" id="table-filter-input">

        </form>
        <table-grid
          :data="gridData"
          :columns="gridColumns"
          :filter-key="searchQuery">
        </table-grid>
      </div>

      <script>
          // register the grid component
          Vue.component('table-grid', {
            template: '#grid-template',
            props: {
              data: Array,
              columns: Array,
              filterKey: String
            },
            data: function () {
              var sortOrders = {}
              this.columns.forEach(function (key) {
                sortOrders[key] = 1
              })
              return {
                sortKey: '',
                sortOrders: sortOrders
              }
            },
            computed: {
              filteredData: function () {
                var sortKey = this.sortKey
                var filterKey = this.filterKey && this.filterKey.toLowerCase()
                var order = this.sortOrders[sortKey] || 1
                var data = this.data
                if (filterKey) {
                  data = data.filter(function (row) {
                    return Object.keys(row).some(function (key) {
                      return String(row[key]).toLowerCase().indexOf(filterKey) > -1
                    })
                  })
                }
                if (sortKey) {
                  data = data.slice().sort(function (a, b) {
                    a = a[sortKey]
                    b = b[sortKey]
                    return (a === b ? 0 : a > b ? 1 : -1) * order
                  })
                }
                return data
              }
            },
            filters: {
              tableHeadPrepper: function (str) {
                return (str.charAt(0).toUpperCase() + str.slice(1)).replace(/_/g, ' ')
              }
            },
            methods: {
              sortBy: function (key) {
                this.sortKey = key
                this.sortOrders[key] = this.sortOrders[key] * -1
              },
              goToPermalink: function(entry) {
                if (entry.link !== undefined) {
                  window.location.href = entry.link;
                }
              }
            },
            created: function() {
            }
          })

          // bootstrap the table
          var table = new Vue({
            el: '#table',
            data: {
              searchQuery: '',
              gridColumns: {!! json_encode( $keys ) !!},
              gridData: {!! json_encode( $data ) !!}
            }
          })

        </script>
    </div>
  </section>

@endsection

@section('widget-panel__content')

  {{-- <section class="widget-panel__section" data-section-name="actions">
    <h3 class="widget-panel__section__title">Actions</h3>
    <ul class="widget-panel__link-group">
      <li><a class="widget-panel__link" href="{{url('admin/page/create')}}">Create new page</a></li>
    </ul>
  </section> --}}

@endsection

resources/views/atrium/pages/pages-edit.blade.php
@extends('atrium.layouts.app')

@section('view-header__content')
  <h1 class="view-title">Edit Page: {{ $page->title }}</h1>
@endsection

@section('view-main__body')

<form class="view-main__content__editor-form form--standard is-flex-grid" action="{{ url('admin/page', $page) }}" method="POST">
  <input type="hidden" name="_method" value="PUT">
  {{ csrf_field() }}
<section class="view-main__section">
  <header class="view-main__section__header">
    <h3 class="view-main__section__title">Page Contents</h3>
  </header>

  <div class="flex-row">
    <div class="input--text flex-2-fr {{ $errors->has('title') ? ' has-error' : ''}}">
      <label for="ef-page-title">Page Title</label>
      <input name="title" id="ef-page-title" type="text" placeholder="Page Title" value="{{ old('title') ? old('title') : $page->title }}"/>
    </div>
    <div class="input--text flex-2-fr">
      <label for="ef-page-slug">Slug</label>
      <input name="slug" id="ef-page-slug" type="text" placeholder="Page Slug" value="{{ (old('slug')) ? old('slug') : $page->slug }}"/>
    </div>
    <div class="input--text flex-2-fr {{ $errors->has('header') ? ' has-error' : ''}}">
      <label for="ef-page-header">Header</label>
      <input name="header" id="ef-page-header" type="text" placeholder="Page Header" value="{{ old('header') ? old('header') : $page->header }}"/>
    </div>
  </div>

  <div class="flex-row">
    <div class="flex-row">
      <div class="input--textarea flex-6-fr {{ $errors->has('content') ? ' has-error' : ''}}">
        <label for="ckeditor">Content</label>
        <textarea name="body" id="ckeditor" rows="10">{!! old('body') ? old('body') : $page->body !!}</textarea>
      </div>
    </div>
  </div>

</section>

{{-- <section class="view-main__section">
  <header class="view-main__section__header">
    <h3 class="view-main__section__title">Header Image</h3>
  </header>

  <div class="flex-row">
    <div class="input--file">
      <input type="file" / name="image">
    </div>
  </div>

</section> --}}

<section class="view-main__section">
  <header class="view-main__section__header">
    <h3 class="view-main__section__title">Seo And Other Page Options</h3>
  </header>

  <div class="flex-row">
    <div class="input--text flex-2-fr">
      <label for="ef-post-title">Title Tag</label>
      <input name="titleTag" id="ef-post-titletag" type="text" placeholder="Title Tag" value="{{ (old('titleTag')) ? old('titleTag') : $page->titleTag }}" required/>
    </div>

    <div class="input--text flex-4-fr">
      <label for="ef-post-metadescription">Meta Description</label>
      <input name="metaDescription" id="ef-post-metadescription" type="text" placeholder="Meta Description" value="{{ (old('metaDescription')) ? old('metaDescription') : $page->metaDescription }}" required/>
    </div>
  </div>

  <div class="flex-row">
    <div class="input--text flex-3-fr {{ $errors->has('linkName') ? ' has-error' : ''}}">
      <label for="ef-link-name">Link Name</label>
      <input name="linkName" id="ef-link-name" type="text" placeholder="Link Name" value="{{ old('linkName') ? old('linkName') : $page->linkName }}"/>
    </div>

    <div class="input--toggle">
      <input name="position" type="checkbox" class="input--toggle__checkbox" id="toggle-second-toggle" @if($page->position) checked @endif/>
      <label class="input--toggle__label" for="toggle-second-toggle">Show page in footer</label>
    </div>
  </div>

</section>

<div class="button-group">
  <button type="submit" class="btn--std--primary">
    <svg width="16" height="16" viewbox="0 0 16 16"><use xlink:href="#icon-check"></use></svg>
    <span class="button-label">Save</span>
  </button>
  <a href="{{ url('admin/page') }}" class="btn--std">
    <svg width="16" height="16" viewbox="0 0 16 16"><use xlink:href="#icon-close"></use></svg>
    <span class="button-label">Cancel</span>
  </a>
</div>

</form>
@endsection

@section('widget-panel__content')

  <section class="widget-panel__section" data-section-name="actions">
    <h3 class="widget-panel__section__title">Actions</h3>
    <ul class="widget-panel__link-group">
      <form class="" action="{{ url('admin/page', $page) }}" method="post">
        <input type="hidden" name="_method" value="DELETE">
        {{ csrf_field() }}
        <li><button type="submit" class="widget-panel__link" href="">Delete this page</button></li>
      </form>
    </ul>
  </section>

@endsection