routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin'], function () {
    Route::get('/', 'AdminController@Home')->name('admin.home');
    Route::group(['middleware' => 'auth'], function () {
        Route::group(['middleware' => ['role:admin']], function () {
            Route::resource('page', 'PageController');
            Route::resource('product', 'ProductController');
            Route::post('product/reorder', 'ProductController@reorder')->name('product.reorder');
            Route::get('product/type/{type}', 'ProductController@index');
            Route::resource('order', 'OrderController');
            Route::resource('shipping', 'ShippingController');
            Route::resource('social', 'SocialMediaController');
            Route::resource('enquiry', 'EnquiryController');
            Route::resource('lead-conversion-types', 'LeadConversionTypeController');
            Route::resource('user', 'UserController');
            Route::resource('post', 'PostController');
            Route::resource('mainpage', 'MainPageController');
            Route::resource('voucher', 'VoucherController');
            Route::resource('inspireme', 'InspireMeController');
            Route::resource('settings', 'SettingsController');
            
            Route::get('/invoice/{order}', 'OrderController@invoice');

            # Slide controlls:
            Route::get('slider/slide/{slide}/remove-slide/', 'SliderController@removeSlide')->name('slider.remove-slide');
            Route::get('slider/slide/{slide}/remove-background/', 'SliderController@removeBackground')->name('slider.remove-slide-background');
            Route::get('slider/slide/{slide}/remove-item/', 'SliderController@removeItem')->name('slider.remove-slide-item');

            Route::get('email-templates', 'EmailTemplateController@index')->name('emailTemplates.index');
            Route::resource('email-template', 'EmailTemplateController');

            Route::get('video-post', 'PostController@vlogIndex'); 
            Route::post('video-post', 'PostController@storeVlog'); 
            Route::post('video-post/{postId}/delete', 'PostController@destroyVlog');
            Route::post('video-post/edit/{postId}', 'PostController@updateVlog');




            Route::get('video-post/{postId}/edit', 'PostController@editVlog');
            Route::get('video-post/create', 'PostController@createVlog');
            Route::get('mailing-list', 'EnquiryController@mailingListIndex')->name('mailinglist');


            Route::get('statistics', 'StatisticsController@getStatistics')->name('statistics');

            Route::get('profile', 'UserController@adminProfileIndex')->name('admin.profile');
            Route::post('update-profile/{user}', 'UserController@adminProfileUpdate');
            Route::get('logout', 'Auth\LoginController@logOut')->name('login.logout');

            Route::get('/module-sheet', 'AdminController@moduleSheet')->name('admin.module-sheet');
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*
*
*/

Route::post('/email-share', 'SocialMediaController@emailShare')->name('email.share');
Route::get('products/json','ProductsContoller@getProductsJson')->name('products.getJson');
Route::get('/shipping-json', 'ShippingController@getCountryJson')->name('shipping.getCountryJson');
Route::get('/share/{id}', 'MainPageController@share')->name('mainpage.share');
Route::get('/', 'MainPageController@home')->middleware('set.ip.currency')->name('home');
Route::get('home/', 'MainPageController@homeRedirect')->middleware('set.ip.currency')->name('homeRedirect');

Auth::routes();

Route::any('image-generate', 'ImageController@imageGenerate')->name('image.generate');

route::post('share-count', 'SocialMediaController@incrementShareCount')->name('socialmedia.incrementShare');
Route::get('join', 'Auth\LoginController@join')->name('login.join');
Route::get('signed-in/', 'Auth\LoginController@signedIn')->name('login.signedIn');
Route::get('accessories', 'ProductController@indexAccessories')->name('accessories');
Route::get('aboutus', 'MainPageController@aboutUs')->name('aboutus');
Route::get('differences', 'MainPageController@differences' )->name('differences');
Route::get('contact', 'MainPageController@contact')->name('contact');
Route::get('contact-success', 'MainPageController@contactSuccess')->name('contact-success');
// Route::get('customise', 'CustomiserController@index')->name('customise');
Route::get('our-straps', 'CustomiserController@index')->name('customise');

//TODO: CART DISABLED FOR NOW
Route::get('cart', 'CartController@cart')->name('cart');

Route::post('apply-voucher', 'VoucherController@apply')->name('voucher.apply');
Route::get('remove-voucher', 'VoucherController@remove')->name('voucher.remove');
// Route::get('cart', function () {
//     return redirect()->back();
// })->name('cart');

Route::post('checkout', 'CheckoutController@post')->name('checkout');
Route::get('checkout-login', 'CheckoutController@checkoutLogin')->name('checkout-login');
Route::post('checkout/guest', 'CheckoutController@guest')->name('checkout.guest');

Route::post('checkout/complete', 'CheckoutController@checkout')->name('checkout.complete');
Route::get('completed/', 'CheckoutController@completed')->name('checkout.completed');

Route::get('checkout/failed', 'CheckoutController@checkoutFailed')->name('checkout.failed');

Route::get('order-success', 'OrderController@orderSuccess')->name('order-success');

Route::post('enquiry/send', 'EnquiryController@send')->name('enquiry.send');
Route::post('newsletter/subscribe', 'EnquiryController@signupForNewsletter')->name('newsletter.subscribe');

Route::get('unsubscribe/{email}', 'EnquiryController@unsubscribeFromNewsletter');


Route::post('cart/remove', 'CartController@remove')->name('cart.remove');
Route::post('cart/qty', 'CartController@qty')->name('cart.qty');
Route::post('cart/{product}', 'CartController@add')->name('cart.add');
Route::get('cart/destroy', 'CartController@destroy')->name('cart.destroy');
Route::get('cart/set/currency/{currency}', 'CartController@setCurrency')->name('cart.setCurrency');

Route::post('customiser/assemble', 'CustomiserController@assemble')->name('customiser.assemble');

Route::resource('customiser', 'CustomiserController');


Route::get('blog', 'PostController@allPosts')->name('blog');
Route::get('blog/{post}', 'PostController@show')->name('blog.show');
Route::get('blog/{post}/share/{socialMedia}', 'PostController@share')->name('blog.share');

Route::get('mail-test/order/{order}/','CheckoutController@mailTest')->name('checkout.mailTest');
Route::get('mail-test/order-admin/{order}/', 'CheckoutController@adminMailTest')->name('checkout.adminMailTest');
// Pages Controller to control user defined pages:
Route::get('{slug}', 'PageController@show');

resources/views/atrium/modules/atrium-dotted-icon.blade.php
<svg viewbox="0 0 42 42" width="42" height="42"
  @if (!empty($alert))
    @if ( $alert === true)
      class="has-new-entry @if ($count > 99)is-big-dot @endif @if ($count > 999)is-bigger-dot @endif"
    @endif
  @endif
>
  <use xlink:href="#icon-{{ $icon }}" width="24" height="24" x="9" y="9" viewbox="0 0 24 24"/>
  @if (!empty($count))
    <circle class="alert-dot" cx="30" cy="14" r="4" />
    @if ( $count > 999 ) {{ $count = '999+' }} @endif
    <text x="30" y="17" text-anchor="middle">{{ $count }}</text>
  @endif

</svg>

@if (!empty($title))
  <span class="icon-hidden-label">{{ $title }}</span>
@endif

resources/views/atrium/modules/breadcrumbs.blade.php
{{-- @if ($breadcrumbs)
  <p class="view-title-breadcrumbs">
    @foreach ($breadcrumbs as $breadcrumb)
      @if (!$breadcrumb->last)
        <a href="{{ $breadcrumb->url }}" title="{{ $breadcrumb->title }}">{{ $breadcrumb->title }}
          @if(isset($breadcrumb->id)) (ID <data data-name="user-id" value="{{$breadcrumb->id}}">{{ $breadcrumb->id }}</data>) @endif
        </a>
      @else
        <a href="{{ $breadcrumb->url }}" title="{{ $breadcrumb->title }}" class="is-current">{{ $breadcrumb->title }}
          @if(isset($breadcrumb->id)) (ID <data data-name="user-id" value="{{$breadcrumb->id}}">{{ $breadcrumb->id }}</data>) @endif
        </a>
      @endif
    @endforeach
  </p>
@endif --}}

resources/views/atrium/modules/head.blade.php
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>{{ $pageTitle or 'Welcome' }} | {{ config('app.name', 'Laravel') }}</title>

<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<!-- TypeKit -->

<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/vue-multiselect@2.0.0"></script>

<script src="https://use.typekit.net/cjt2wtd.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>

<link href="https://fonts.googleapis.com/css?family=Poppins:500,700" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="{{ mix('atrium-assets/css/atrium.css') }}" />
<script type="text/javascript" src="{{ asset('atrium-assets/js/vendors/jquery.js') }}"></script>

resources/views/atrium/modules/nav-sidebar.blade.php
<div class="view-nav-sidebar-wrapper">
  <span class="view-nav-sidebar__overlay"></span>
  <button class="view-nav-item hamburger-button" id="site-nav-toggle">
  @component('atrium.modules.atrium-dotted-icon', ['icon' => 'menu'])
  @endcomponent
  </button>
  <nav id="view-nav" class="view-nav">
    <ul class="view-nav__list">
      {{-- <li class="view-nav__li">
        <a class="view-nav__item" title="" href="{{ url('admin/') }}">
        @component('atrium.modules.atrium-dotted-icon', ['icon' => 'home'])
        @endcomponent
        <span class="view-nav__item__label">Home</span>
        </a>
      </li> --}}
      {{-- <hr /> --}}
      <li class="view-nav__li has-submenu">
        {{-- <a class="view-nav__item is-parent" title="" href="{{ url('admin/product') }}">
        @component('atrium.modules.atrium-dotted-icon', ['icon' => 'cube'])
        @endcomponent
        <span class="view-nav__item__label">Products</span>
        </a> --}}
        <ul class="view-nav__submenu">
          <li class="view-nav__submenu__li">
            <a class="view-nav__submenu__item" title="" href="{{ url('admin/product') }}">
            <span class="view-nav__submenu__item__label">All Products</span>
            </a>
          </li>
          @foreach (App\Product\Type::all() as $type)
          <li class="view-nav__submenu__li">
            <a class="view-nav__submenu__item" title="" href="{{ url('admin/product/type/' . $type->id) }}">
            <span class="view-nav__submenu__item__label">{{ str_plural($type->name, 2) }}</span>
            </a>
          </li>
          @endforeach
          {{-- <li class="view-nav__submenu__li">
            <a class="view-nav__submenu__item" title="" href="{{ url('admin/product/create') }}">
            <span class="view-nav__submenu__item__label">Create new</span>
            </a>
          </li> --}}
        </ul>
      </li>
      <hr />
      <li class="view-nav__li">
        <a class="view-nav__item" title="" href="{{ url('admin/order') }}">
        @component('atrium.modules.atrium-dotted-icon', ['icon' => 'euro'])
        @endcomponent
        <span class="view-nav__item__label">Orders</span>
        </a>
      </li>
      <li class="view-nav__li">
        <a class="view-nav__item" title="" href="{{ url('admin/voucher') }}">
        @component('atrium.modules.atrium-dotted-icon', ['icon' => 'euro'])
        @endcomponent
        <span class="view-nav__item__label">Vouchers Codes</span>
        </a>
      </li>
      <li class="view-nav__li">
        <a class="view-nav__item" title="" href="{{ url('admin/shipping') }}">
        @component('atrium.modules.atrium-dotted-icon', ['icon' => 'truck'])
        @endcomponent
        <span class="view-nav__item__label">Shipping Options</span>
        </a>
      </li>
      <li class="view-nav__li">
        <a class="view-nav__item" title="" href="{{ route('lead-conversion-types.index') }}">
        @component('atrium.modules.atrium-dotted-icon', ['icon' => 'truck'])
        @endcomponent
        <span class="view-nav__item__label">Lead Conversion Types</span>
        </a>
      </li>
      <li class="view-nav__li">
        <a class="view-nav__item" title="" href="{{ url('admin/user') }}">
        @component('atrium.modules.atrium-dotted-icon', ['icon' => 'file'])
        @endcomponent
        <span class="view-nav__item__label">Users</span>
        </a>
      </li>
      <li class="view-nav__li">
        <a class="view-nav__item" title="" href="{{ url('admin/inspireme') }}">
        @component('atrium.modules.atrium-dotted-icon', ['icon' => 'file'])
        @endcomponent
        <span class="view-nav__item__label">Inspire-Me Presets</span>
        </a>
      </li>
      <li class="view-nav__li">
        <a class="view-nav__item" title="" href="{{ url('admin/mainpage') }}">
        @component('atrium.modules.atrium-dotted-icon', ['icon' => 'file'])
        @endcomponent
        <span class="view-nav__item__label">Main Pages</span>
        </a>
      </li>
      <li class="view-nav__li">
        <a class="view-nav__item" title="" href="{{ url('admin/page') }}">
        @component('atrium.modules.atrium-dotted-icon', ['icon' => 'file'])
        @endcomponent
        <span class="view-nav__item__label">Pages</span>
        </a>
      </li>
      <li class="view-nav__li">
        <a class="view-nav__item" title="" href="{{ url('admin/post') }}">
        @component('atrium.modules.atrium-dotted-icon', ['icon' => 'file'])
        @endcomponent
        <span class="view-nav__item__label">Blogs</span>
        </a>
      </li>
      <li class="view-nav__li">
        <a class="view-nav__item" title="" href="{{ url('admin/video-post') }}">
        @component('atrium.modules.atrium-dotted-icon', ['icon' => 'file'])
        @endcomponent
        <span class="view-nav__item__label">Vlogs</span>
        </a>
      </li>
      <li class="view-nav__submenu__li">
        <a class="view-nav__submenu__item" title="" href="{{ url('admin/social') }}">
          <span class="view-nav__submenu__item__label">Social Media</span>
        </a>
      </li>
      <li class="view-nav__submenu__li">
        <a class="view-nav__submenu__item" title="" href="{{ url('admin/enquiry') }}">
          <span class="view-nav__submenu__item__label">Enquiries</span>
        </a>
      </li>
      <li class="view-nav__submenu__li">
        <a class="view-nav__submenu__item" title="" href="{{ url('admin/mailing-list') }}">
          <span class="view-nav__submenu__item__label">Mailing List</span>
        </a>
      </li>
      <hr>
      <li class="view-nav__submenu__li">
        <a class="view-nav__submenu__item" title="" href="{{ route('statistics') }}">
          <span class="view-nav__submenu__item__label">Statistics</span>
        </a>
      </li>
      <li class="view-nav__submenu__li">
        <a class="view-nav__submenu__item" title="" href="{{ route('emailTemplates.index') }}">
          <span class="view-nav__submenu__item__label">Email templates</span>
        </a>
      </li>
      <li class="view-nav__submenu__li">
        <a class="view-nav__submenu__item" title="" href="{{ url('admin/settings') }}">
          <span class="view-nav__submenu__item__label">Settings</span>
        </a>
      </li>
      {{-- <li class="view-nav__li">
        <a class="view-nav__item" title="" href="">
        @component('atrium.modules.atrium-dotted-icon', ['icon' => 'cog-complex'])
        @endcomponent
        <span class="view-nav__item__label">Global Settings</span>
        </a>
      </li> --}}
    </ul>
  </nav>
</div>

resources/views/atrium/modules/notif-card.blade.php
<section
  class="notif-card"
  data-notif-type="{{ $type }}">
  @if (!isset($notifIcon))
    @php
      if ($type === 'attention') {
        $notifIcon = 'attention';
      } elseif ($type === 'alert') {
        $notifIcon = 'warning';
      } else {
        $notifIcon = 'info';
      }
    @endphp
  @endif
  <header class="notif-card__header">
    <svg class="notif-card__icon" width="18" height="18" viewbox="0 0 18 18"><use xlink:href="#icon-{{ $notifIcon }}"></use></svg>
    <h3 class="notif-card__title">
      @if ( !empty($title) )
        {{ $title }}
      @else
        Notification
      @endif
    </h3>
    <button type="button" data-action="dismiss-notif" class="module-close-button">
      <svg width="14" height="14" viewbox="0 0 14 14"><use xlink:href="#icon-close"></use></svg>
    </button>
  </header>

  @if ( !empty($message) )
    <div class="notif-card__body">
      {{ $message }}
    </div>
  @endif

  <footer class="notif-card__footer">
    <div class="button-group--pill">
      <button class="btn--pill--primary" type="button" data-action="dismiss-notif">OK</button>
      @if ( !empty($undoable) )
        @if ($undoable === true)
          <button class="btn--pill" type="button">Undo</button>
        @endif
      @endif
    </div>
      @if ( !empty($customActions) )
        {{ $customActions }}
      @endif
  </footer>

</section>

resources/views/atrium/modules/search-bar.blade.php
<section id="widget-panel__search-bar" class="widget-panel__section is-search" data-section-name="search">
  <form class="widget-panel__search-bar">
    @if ( $target === 'account' )
      <input type="search" placeholder="Search for an account" />
    @endif
    <button type="submit"/>
      <svg width="18" height="18" viewbox="0 0 18 18"><use xlink:href="#icon-search"></use></svg>
    </button>
  </form>
</section>

resources/views/atrium/modules/stat-card.blade.php
<li class="statistics-card" data-stat-type="{{ $type }}">
  <h3 class="statistics-card__title">{{ $title }}</h3>
  <em class="statistics-card__stat">{{ $stat }}</em>
</li>

resources/views/atrium/modules/user-icon.blade.php
@if (isset($size))
  @php $iconSize = $size @endphp
@else
  @php $iconSize = 42 @endphp
@endif

<svg class="user-icon" width="{{$iconSize}}" height="{{$iconSize}}" viewbox="0 0 {{$iconSize}} {{$iconSize}}">
  <title>{{ $userName }}'s Profile Icon</title>
  @if (isset($iconPath))
    <image class="user-icon__img"
           clip-path="url(#user-icon-circle)"
           x="0" y="0"
           xlink:href="{{ asset($iconPath) }}"
           alt="{{ $userName }}'s Profile Icon"
           width="{{$iconSize}}"
           height="{{$iconSize}}"/>
  @else
    <g clip-path="url(#user-icon-{{ $iconShape or 'circle' }})">
      <rect width="{{$iconSize}}" height="{{$iconSize}}" fill="#ddd"></rect>
      <rect width="{{$iconSize}}" height="{{$iconSize}}" fill="url(#gradient--primary)"></rect>
      <use xlink:href="#icon-person" x="{{ $iconSize * 0.19 }}" y="{{ $iconSize * 0.17 }}" width="{{ $iconSize * 0.62}}" height="{{ $iconSize * 0.62}}" fill="white" fill-opacity="0.618" ></use>
    </g>
  @endif
</svg>

resources/views/atrium/modules/view-backstage.blade.php
<section class="view-backstage"
  style="position: absolute; width: 0; height: 0; overflow: hidden; margin: 0; bottom: 0;">
  <svg viewBox="0 0 24 24">

    <?php
        $colorNames = array(
          'primary' ,
          'secondary' ,
          'tertiary',
          'quaternary',
          'accent' ,
          'background',
          'foreground',
          'light' ,
          'shadow' ,
          'median',
          'positive',
          'neutral',
          'attention',
          'alert',
          'text');
        foreach( $colorNames as &$color ) {
          echo '<linearGradient id="gradient--' . $color . '" gradientTransform="rotate(50)">
            <stop offset="0.4" />
            <stop offset="1" />
          </linearGradient>';
        }
        ?>

    <clipPath id="user-icon-circle" clipPathUnits="objectBoundingBox">
      <circle cx=".5" cy=".5" r=".5" />
    </clipPath>


    @include('atrium.theming.symbols')

  </svg>

  @include('atrium.assets.icons')

</section>

resources/views/atrium/modules/view-footer.blade.php
  {{-- @component('atrium.modules.notif-card', [
    'type' => 'neutral',
    'context' => 'action-success',
    'notifIcon' => 'person',
    'undoable' => true
  ])
    @slot('title')
      You have successfully deactivated the account <data data-name="user-id" class="u-font-mono" value="JE9290">inkjetink</data>.
    @endslot
    @slot('message')
      <p>You can reactivate this account by going to its detail page.</p>
    @endslot
    @slot('customActions')
      <button class="button--pill" type="button">View Account Details</button>
    @endslot
    positive alert attention neutral
  @endcomponent --}}
@if(session()->has('notification'))
  <div class="view-notif-card-stack" id="view-notif-card-stack">
    @component('atrium.modules.notif-card', [
      'type' => session()->get('type'),
      'context' => 'system'
    ])
    @slot('title')
      {{ session()->get('notification') }}
    @endslot
  @endcomponent
  </div>
@endif

@if($errors->any())
  <div class="view-notif-card-stack" id="view-notif-card-stack">
    @component('atrium.modules.notif-card', [
      'type' => 'alert',
      'context' => 'system'
    ])
    @slot('title')
      Required fields!
    @endslot
    @slot('message')
      @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
      @endforeach
    @endslot
  @endcomponent
  </div>
@endif
<footer class="view-footer">

  <div class="view-footer__content">
    <span class="view-footer__content__item is-copyright">
      <small>Powered by <a href="" title="" target="_blank">Atrium</a> CMS.</small>
      <small>&copy; 2017 <a href="http://www.viralbamboo.com/" title="Viralbamboo Digital Agency" target="_blank">Viralbamboo</a> Ltd.</small>
    </span>
    {{-- <span class="view-footer__content__item">
      <svg width="14" height="14" viewbox="0 0 14 14"><use xlink:href="#icon-person"/ ></svg>
      78 Online Users
    </span> --}}
    {{-- <a class="view-footer__controls__item" href="" title=""></a> --}}
  </div>

  @yield('footer')

  <div class="view-footer-roadsigns">
    {{-- <a class="view-footer-roadsign__item" href="{{ url('admin/module-sheet') }}" title="">
      <svg width="14" height="14" viewbox="0 0 14 14"><use xlink:href="#icon-wrench"/ ></svg>
      <span>Atrium Module Sheet</span>
    </a> --}}
    <a class="view-footer-roadsign__item is-primary" href="" title="">
      <svg width="14" height="14" viewbox="0 0 14 14"><use xlink:href="#icon-arrow"/ ></svg>
      <span>View Site</span>
    </a>
  </div>

</footer>


</div>

<script type="text/javascript" src="{{ asset('atrium-assets/js/vendors/gsap/uncompressed/TweenMax.js') }}"></script>
<script type="text/javascript" src="{{ asset('atrium-assets/js/vendors/ckeditor/ckeditor.js') }}"></script>

<script>
if (document.getElementById('ckeditor')) CKEDITOR.replace('ckeditor');
if (document.getElementById('ckeditor1')) CKEDITOR.replace('ckeditor1');
if (document.getElementById('ckeditor2')) CKEDITOR.replace('ckeditor2');
if (document.getElementById('ckeditor3')) CKEDITOR.replace('ckeditor3');
if (document.getElementById('ckeditor4')) CKEDITOR.replace('ckeditor4');
</script>

<script type="text/javascript" src="{{ asset('atrium-assets/js/dist/init.js') }}"></script>
<script type="text/javascript" src="{{ asset('atrium-assets/js/dist/ui.js') }}"></script>
<script type="text/javascript" src="{{ asset('atrium-assets/js/dist/popups.js') }}"></script>
<script type="text/javascript" src="{{ asset('atrium-assets/js/dist/notif-cards.js') }}"></script>
<script type="text/javascript" src="{{ asset('atrium-assets/js/dist/index.js') }}"></script>

<script src="{{ mix('js/app.js') }}"></script>

resources/views/atrium/modules/view-header.blade.php
<header class="view-header">
  <div class="view-header__logo-container">
    <a href="{{ url('')}}" title="Vulcan Home" class="view-header-logo__permalink" target="_blank">
      <svg width="120" height="60">
        <use xlink:href="#{{ $siteNameStr }}-logo"></use>
      </svg>
      <span class="view-header-logo__label">{{ config('app.name', 'Atrium') }}</span>
    </a>
  </div>
  <div class="view-header__main">
    <div class="view-header__main__container">
      @yield('view-header__content')
      {{-- {!! Breadcrumbs::renderIfExists() !!} --}}
    </div>
  </div>
    <div class="view-header__controls">
      {{-- <a class="view-header__control u-desktop" href="/admin/home" title="Atrium Home">
        @component('atrium.modules.atrium-dotted-icon', [
          'icon' => 'home',
          'title' => 'Home',
          'alert' => false,
        ])
        @endcomponent
      </a> --}}
      {{-- <a class="view-header__control">
        @component('atrium.modules.atrium-dotted-icon', [
          'icon' => 'notification',
          'title' => 'Notification',
          'alert' => true,
          'count' => 4
        ])
        @endcomponent
      </a>
      <a class="view-header__control">
        @component('atrium.modules.atrium-dotted-icon', [
          'icon' => 'message',
          'title' => 'Messages',
          'alert' => true,
          // if alert is set to true, a red dot will show up.
          'count' => 889
          // count is the number to show in the bubble when hovered.
        ])
      @endcomponent --}}
    </a>
    <div class="view-header__user-icon-button">
      <a class="user-icon-link">
        @component('atrium.modules.user-icon', [
          'iconShape' => 'circle'
        ])
        @slot('userName') {{ Auth::user()->name }} @endslot
        @endcomponent
        <span class="user-name-tag" title="{{ Auth::user()->name }}">{{ Auth::user()->name }}</span>
      </a>
      <ul class="view-header__user-menu">
        <li><a href="{{ route('admin.profile') }}">View your profile</a></li>
        <li><a href="{{ env('APP_URL') }}" target="_blank">Go to Vulcan Homepage</a></li>
        <li><a title="Log out" href="{{ url('admin/logout')}}">Log out</a></li>
      </ul>
    </div>


  </div>

</header>